import json
import os
import platform
import shutil
import subprocess
import sys
import uuid
from datetime import datetime, timedelta
from pathlib import Path

from core.reminder_escalation import (
    cancel_by_id as cancel_escalation_by_id,
    normalize_config as normalize_escalation_config,
    register as register_escalation,
)

_CNW: dict = (
    {"creationflags": subprocess.CREATE_NO_WINDOW}
    if platform.system() == "Windows" else {}
)

def _base_dir() -> Path:
    if getattr(sys, "frozen", False):
        return Path(sys.executable).parent
    return Path(__file__).resolve().parent.parent


def _get_os() -> str:
    _sys = platform.system()
    if _sys == "Darwin":
        return "mac"
    if _sys == "Linux":
        return "linux"
    return "windows"


def _scripts_dir() -> Path:
    d = Path.home() / ".jarvis" / "reminders"
    d.mkdir(parents=True, exist_ok=True)
    return d


def _reminder_store() -> Path:
    d = _base_dir() / "memory"
    d.mkdir(parents=True, exist_ok=True)
    return d / "reminders.json"


def _read_managed() -> list[dict]:
    try:
        raw = json.loads(_reminder_store().read_text(encoding="utf-8"))
        return raw if isinstance(raw, list) else []
    except (FileNotFoundError, json.JSONDecodeError, OSError):
        return []


def _write_managed(records: list[dict]) -> None:
    path = _reminder_store()
    path.write_text(json.dumps(records, indent=2, ensure_ascii=False) + "\n",
                    encoding="utf-8")


def _cancel_job(job_id: str) -> None:
    """Best-effort cancellation for a one-shot native scheduler job."""
    if not job_id:
        return
    os_name = _get_os()
    try:
        if os_name == "windows":
            subprocess.run(
                ["schtasks", "/Delete", "/TN", job_id, "/F"],
                capture_output=True, text=True, **_CNW,
            )
        elif os_name == "mac":
            label = job_id if job_id.startswith("com.jarvis.reminder.") else (
                f"com.jarvis.reminder.{job_id}"
            )
            plist = Path.home() / "Library" / "LaunchAgents" / f"{label}.plist"
            subprocess.run(["launchctl", "unload", str(plist)],
                           capture_output=True, text=True)
            plist.unlink(missing_ok=True)
        elif shutil.which("systemctl"):
            subprocess.run(
                ["systemctl", "--user", "stop", job_id],
                capture_output=True, text=True,
            )
    except (OSError, subprocess.SubprocessError):
        pass


def _safe_remove_script(record: dict) -> None:
    try:
        Path(str(record.get("script_path", ""))).unlink(missing_ok=True)
    except (OSError, ValueError):
        pass


def _notify_now(message: str) -> None:
    """Show the same local notification used by the generated one-shot script."""
    notified = False
    try:
        from plyer import notification
        notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
        notified = True
    except Exception:
        pass
    if platform.system() == "Windows" and not notified:
        try:
            from win10toast import ToastNotifier
            ToastNotifier().show_toast(
                "J.A.R.V.I.S Reminder", message, duration=15, threaded=False
            )
            notified = True
        except Exception:
            pass
    if platform.system() == "Darwin" and not notified:
        try:
            subprocess.run(
                ["osascript", "-e",
                 'display notification "{}" with title "J.A.R.V.I.S Reminder"'.format(
                     message.replace('"', "")
                 )],
                check=False,
            )
            notified = True
        except Exception:
            pass
    if platform.system() == "Linux" and not notified:
        try:
            subprocess.run(
                ["notify-send", "--urgency=normal", "--expire-time=15000",
                 "J.A.R.V.I.S Reminder", message],
                check=False,
            )
        except Exception:
            pass


def _write_managed_script(reminder_id: str) -> Path:
    task_name = f"JARVISReminder_{reminder_id}"
    path = _scripts_dir() / f"{task_name}.py"
    base = str(_base_dir())
    path.write_text(
        "# Auto-generated by JARVIS reminder — do not edit\n"
        "import sys\n"
        f"sys.path.insert(0, {base!r})\n"
        "try:\n"
        f"    from actions.reminder import fire_managed_reminder\n"
        f"    fire_managed_reminder({reminder_id!r})\n"
        "finally:\n"
        "    try:\n"
        "        from pathlib import Path\n"
        "        Path(__file__).unlink(missing_ok=True)\n"
        "    except Exception:\n"
        "        pass\n",
        encoding="utf-8",
    )
    path.chmod(0o600)
    return path


def _next_occurrence(target: datetime, frequency: str,
                     weekdays: list[int] | None = None) -> datetime | None:
    frequency = (frequency or "once").lower()
    if frequency == "once":
        return None
    if frequency == "daily":
        return target.replace(second=0, microsecond=0) + timedelta(days=1)
    valid_days = sorted({int(day) for day in (weekdays or []) if 0 <= int(day) <= 6})
    if not valid_days:
        valid_days = [target.weekday()]
    candidate = target.replace(second=0, microsecond=0) + timedelta(days=1)
    for _ in range(7):
        if candidate.weekday() in valid_days:
            return candidate
        candidate += timedelta(days=1)
    return None


def _schedule_managed_record(record: dict) -> bool:
    target = datetime.fromisoformat(str(record["next_trigger"]))
    task_name = f"JARVISReminder_{record['id']}"
    script_path = _write_managed_script(str(record["id"]))
    os_name = _get_os()
    try:
        if os_name == "windows":
            job_id = _schedule_windows(target, task_name, script_path, record["message"])
        elif os_name == "mac":
            job_id = _schedule_mac(target, task_name, script_path)
        else:
            job_id = _schedule_linux(target, task_name, script_path)
    except Exception:
        script_path.unlink(missing_ok=True)
        raise
    if not job_id:
        script_path.unlink(missing_ok=True)
        return False
    record["job_id"] = job_id
    record["script_path"] = str(script_path)
    return True


def _normalise_managed_input(
    message: str, target: datetime, frequency: str, weekdays: list[int] | None,
    escalation: dict | None,
) -> dict:
    frequency = (frequency or "once").strip().lower()
    if frequency not in {"once", "daily", "weekly"}:
        raise ValueError("Schedule must be once, daily, or weekly.")
    if target <= datetime.now():
        raise ValueError("That time has already passed.")
    days = sorted({int(day) for day in (weekdays or []) if 0 <= int(day) <= 6})
    if frequency == "weekly" and not days:
        days = [target.weekday()]
    normalized = normalize_escalation_config(escalation or {})
    if normalized["enabled"]:
        if not normalized["whatsapp_contact_name"]:
            normalized["whatsapp_contact_name"] = "Baba"
        if not normalized["messenger_contact_name"]:
            normalized["messenger_contact_name"] = "شريف كمال"
    return {
        "id": f"managed-{uuid.uuid4().hex}",
        "message": _sanitise(message or "Reminder"),
        "frequency": frequency,
        "weekdays": days,
        "next_trigger": target.replace(second=0, microsecond=0).isoformat(),
        "enabled": True,
        "escalation": normalized,
        "created_at": datetime.now().isoformat(),
        "updated_at": datetime.now().isoformat(),
    }


def create_managed_reminder(
    message: str, target: datetime, frequency: str = "once",
    weekdays: list[int] | None = None, escalation: dict | None = None,
) -> dict:
    """Create a persistent reminder while reusing the native OS scheduler."""
    record = _normalise_managed_input(message, target, frequency, weekdays, escalation)
    records = _read_managed()
    records.append(record)
    _write_managed(records)
    try:
        if not _schedule_managed_record(record):
            raise RuntimeError("The operating system scheduler rejected the reminder.")
    except Exception:
        _write_managed([item for item in records if item["id"] != record["id"]])
        raise
    record["updated_at"] = datetime.now().isoformat()
    _write_managed(records)
    return dict(record)


def list_managed_reminders() -> list[dict]:
    return [dict(item) for item in _read_managed()]


def update_managed_reminder(
    reminder_id: str, message: str, target: datetime, frequency: str,
    weekdays: list[int] | None = None, escalation: dict | None = None,
) -> dict:
    records = _read_managed()
    for record in records:
        if record.get("id") != reminder_id:
            continue
        _cancel_job(str(record.get("job_id", "")))
        _safe_remove_script(record)
        fresh = _normalise_managed_input(message, target, frequency, weekdays, escalation)
        fresh["id"] = reminder_id
        fresh["created_at"] = record.get("created_at", datetime.now().isoformat())
        record.clear()
        record.update(fresh)
        if not _schedule_managed_record(record):
            record["enabled"] = False
            _write_managed(records)
            raise RuntimeError("The operating system scheduler rejected the reminder.")
        _write_managed(records)
        return dict(record)
    raise KeyError("Reminder not found.")


def set_managed_reminder_enabled(reminder_id: str, enabled: bool) -> dict:
    records = _read_managed()
    for record in records:
        if record.get("id") != reminder_id:
            continue
        _cancel_job(str(record.get("job_id", "")))
        _safe_remove_script(record)
        if not enabled:
            cancel_escalation_by_id(reminder_id, "Reminder disabled from Settings.")
        record["job_id"] = ""
        record["script_path"] = ""
        record["enabled"] = bool(enabled)
        record["updated_at"] = datetime.now().isoformat()
        if enabled:
            target = datetime.fromisoformat(str(record["next_trigger"]))
            if target <= datetime.now():
                target = datetime.now().replace(second=0, microsecond=0) + timedelta(minutes=1)
                record["next_trigger"] = target.isoformat()
            if not _schedule_managed_record(record):
                record["enabled"] = False
                raise RuntimeError("The operating system scheduler rejected the reminder.")
        _write_managed(records)
        return dict(record)
    raise KeyError("Reminder not found.")


def delete_managed_reminder(reminder_id: str) -> bool:
    records = _read_managed()
    kept = []
    found = False
    for record in records:
        if record.get("id") == reminder_id:
            found = True
            _cancel_job(str(record.get("job_id", "")))
            _safe_remove_script(record)
            cancel_escalation_by_id(reminder_id, "Reminder deleted from Settings.")
        else:
            kept.append(record)
    if found:
        _write_managed(kept)
    return found


def cancel_scheduled_reminder(reminder_id: str) -> bool:
    """Cancel a voice-created or managed reminder's native scheduler job."""
    records = _read_managed()
    for record in records:
        if record.get("id") == reminder_id:
            return delete_managed_reminder(reminder_id)
    task_name = str(reminder_id)
    _cancel_job(task_name)
    script = _scripts_dir() / f"{task_name}.py"
    existed = script.exists()
    script.unlink(missing_ok=True)
    return existed


def cancel_latest_scheduled_reminder(text: str) -> str | None:
    """Handle cancellation wording for normal reminders as well as escalations."""
    normalized = " ".join((text or "").lower().split())
    markers = (
        "cancel that reminder", "cancel the reminder", "cancel reminder",
        "cancel the baba escalation", "cancel baba escalation",
        "stop the escalation", "stop escalation",
    )
    if not normalized or not any(marker in normalized for marker in markers):
        return None
    records = [
        item for item in _read_managed()
        if item.get("enabled") and item.get("next_trigger")
    ]
    if records:
        record = records[-1]
        reminder_id = str(record.get("id", ""))
        if delete_managed_reminder(reminder_id):
            return reminder_id
    scripts = sorted(
        _scripts_dir().glob("JARVISReminder_*.py"),
        key=lambda path: path.stat().st_mtime,
        reverse=True,
    )
    if scripts:
        reminder_id = scripts[0].stem
        cancel_scheduled_reminder(reminder_id)
        return reminder_id
    return None


def restore_managed_reminders() -> int:
    """Restore enabled persistent schedules after an application restart."""
    records = _read_managed()
    restored = 0
    changed = False
    now = datetime.now()
    for record in records:
        if not record.get("enabled") or not record.get("next_trigger"):
            continue
        try:
            target = datetime.fromisoformat(str(record["next_trigger"]))
            while target <= now:
                next_target = _next_occurrence(
                    target, str(record.get("frequency", "once")), record.get("weekdays")
                )
                if next_target is None:
                    record["enabled"] = False
                    record["next_trigger"] = None
                    changed = True
                    break
                target = next_target
                record["next_trigger"] = target.isoformat()
                changed = True
            if not record.get("enabled"):
                continue
            script = Path(str(record.get("script_path", "")))
            if not script.exists():
                if _schedule_managed_record(record):
                    restored += 1
                    changed = True
        except (TypeError, ValueError, OSError):
            record["enabled"] = False
            record["error"] = "Invalid persisted reminder schedule."
            changed = True
    if changed:
        _write_managed(records)
    return restored


def fire_managed_reminder(reminder_id: str) -> bool:
    """Fire a managed reminder and schedule only its next recurrence."""
    records = _read_managed()
    for record in records:
        if record.get("id") != reminder_id or not record.get("enabled"):
            return False
        _notify_now(str(record.get("message") or "Reminder"))
        escalation = record.get("escalation") or {}
        if isinstance(escalation, dict) and escalation.get("enabled"):
            register_escalation(
                reminder_id=reminder_id,
                target=datetime.now(),
                message=str(record.get("message") or "Reminder"),
                config=escalation,
            )
        current = datetime.fromisoformat(str(record["next_trigger"]))
        next_target = _next_occurrence(
            current, str(record.get("frequency", "once")), record.get("weekdays")
        )
        record["updated_at"] = datetime.now().isoformat()
        if next_target is None:
            record["enabled"] = False
            record["next_trigger"] = None
            record["job_id"] = ""
            _safe_remove_script(record)
        else:
            record["next_trigger"] = next_target.isoformat()
            record["job_id"] = ""
            record["script_path"] = ""
            if not _schedule_managed_record(record):
                record["enabled"] = False
                record["error"] = "Could not schedule the next recurring occurrence."
        _write_managed(records)
        return True
    return False


def cleanup_legacy_test_reminders() -> int:
    """Remove old test records/scripts without touching real reminders."""
    records = _read_managed()
    kept = []
    removed = 0
    for record in records:
        haystack = " ".join(str(record.get(key, "")) for key in ("id", "message")).lower()
        if "test" in haystack:
            _cancel_job(str(record.get("job_id", "")))
            _safe_remove_script(record)
            removed += 1
        else:
            kept.append(record)
    if removed:
        _write_managed(kept)
    for script in _scripts_dir().glob("*test*.py"):
        _cancel_job(script.stem)
        script.unlink(missing_ok=True)
        removed += 1
    return removed


def _sanitise(text: str, max_len: int = 200) -> str:
    return (
        text.replace("\\", "")
            .replace('"', "")
            .replace("'", "")
            .replace("\n", " ")
            .replace("\r", "")
            .strip()
    )[:max_len]

def _write_notify_script(task_name: str, message: str, os_name: str) -> Path:
    script_path = _scripts_dir() / f"{task_name}.py"
    msg_literal = json.dumps(message)  

    if os_name == "windows":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        from win10toast import ToastNotifier
        ToastNotifier().show_toast("J.A.R.V.I.S Reminder", message, duration=15, threaded=False)
        notified = True
    except Exception:
        pass

if not notified:
    try:
        import subprocess
        subprocess.run(["msg", "*", "/TIME:30", message], check=False)
    except Exception:
        pass

try:
    import winsound
    for freq in [800, 1000, 1200]:
        winsound.Beep(freq, 180)
        import time; time.sleep(0.08)
except Exception:
    pass
"""

    elif os_name == "mac":
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        script = 'display notification "{{}}" with title "J.A.R.V.I.S Reminder"'.format(
            message.replace('"', '')
        )
        subprocess.run(["osascript", "-e", script], check=False)
    except Exception:
        pass
"""

    else:  # linux
        notify_block = f"""
message = {msg_literal}
notified = False

try:
    from plyer import notification
    notification.notify(title="J.A.R.V.I.S Reminder", message=message, timeout=15)
    notified = True
except Exception:
    pass

if not notified:
    try:
        import subprocess
        subprocess.run(
            ["notify-send", "--urgency=normal", "--expire-time=15000",
             "J.A.R.V.I.S Reminder", message],
            check=False
        )
    except Exception:
        pass
"""

    script_body = f"""# Auto-generated by J.A.R.V.I.S reminder — do not edit
import sys, os, pathlib
{notify_block}
# Self-delete after firing
try:
    pathlib.Path(__file__).unlink(missing_ok=True)
except Exception:
    pass
"""
    script_path.write_text(script_body, encoding="utf-8")
    script_path.chmod(0o600)   # owner read/write only
    return script_path

def _schedule_windows(target_dt: datetime, task_name: str,
                      script_path: Path, message: str) -> str:
    python_exe = Path(sys.executable)
    pythonw = python_exe.parent / "pythonw.exe"
    if pythonw.exists():
        python_exe = pythonw

    xml_path = _scripts_dir() / f"{task_name}.xml"
    xml_content = (
        '<?xml version="1.0" encoding="UTF-16"?>\n'
        '<Task version="1.2" xmlns="http://schemas.microsoft.com/windows/2004/02/mit/task">\n'
        '  <RegistrationInfo><Description>J.A.R.V.I.S Reminder</Description></RegistrationInfo>\n'
        '  <Triggers><TimeTrigger>\n'
        f'    <StartBoundary>{target_dt.strftime("%Y-%m-%dT%H:%M:%S")}</StartBoundary>\n'
        '    <Enabled>true</Enabled>\n'
        '  </TimeTrigger></Triggers>\n'
        '  <Actions><Exec>\n'
        f'    <Command>{python_exe}</Command>\n'
        f'    <Arguments>"{script_path}"</Arguments>\n'
        '  </Exec></Actions>\n'
        '  <Settings>\n'
        '    <MultipleInstancesPolicy>IgnoreNew</MultipleInstancesPolicy>\n'
        '    <DisallowStartIfOnBatteries>false</DisallowStartIfOnBatteries>\n'
        '    <StopIfGoingOnBatteries>false</StopIfGoingOnBatteries>\n'
        '    <StartWhenAvailable>true</StartWhenAvailable>\n'
        '    <ExecutionTimeLimit>PT5M</ExecutionTimeLimit>\n'
        '    <Enabled>true</Enabled>\n'
        '  </Settings>\n'
        '  <Principals><Principal>\n'
        '    <LogonType>InteractiveToken</LogonType>\n'
        '    <RunLevel>LeastPrivilege</RunLevel>\n'
        '  </Principal></Principals>\n'
        '</Task>'
    )

    xml_path.write_text(xml_content, encoding="utf-16")

    result = subprocess.run(
        ["schtasks", "/Create", "/TN", task_name, "/XML", str(xml_path), "/F"],
        capture_output=True, text=True, **_CNW,
    )

    try:
        xml_path.unlink(missing_ok=True)
    except Exception:
        pass

    if result.returncode != 0:
        script_path.unlink(missing_ok=True)
        err = (result.stderr or result.stdout).strip()
        print(f"[Reminder] ❌ schtasks: {err}")
        return ""  

    return task_name


def _schedule_mac(target_dt: datetime, task_name: str,
                  script_path: Path) -> str:
    agents_dir = Path.home() / "Library" / "LaunchAgents"
    agents_dir.mkdir(parents=True, exist_ok=True)

    label     = f"com.jarvis.reminder.{task_name}"
    plist_path = agents_dir / f"{label}.plist"

    plist_content = f"""<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN"
  "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
  <key>Label</key>             <string>{label}</string>
  <key>ProgramArguments</key>
  <array>
    <string>{sys.executable}</string>
    <string>{script_path}</string>
  </array>
  <key>StartCalendarInterval</key>
  <dict>
    <key>Year</key>   <integer>{target_dt.year}</integer>
    <key>Month</key>  <integer>{target_dt.month}</integer>
    <key>Day</key>    <integer>{target_dt.day}</integer>
    <key>Hour</key>   <integer>{target_dt.hour}</integer>
    <key>Minute</key> <integer>{target_dt.minute}</integer>
  </dict>
  <key>RunAtLoad</key>         <false/>
  <key>StandardOutPath</key>   <string>/dev/null</string>
  <key>StandardErrorPath</key> <string>/dev/null</string>
</dict>
</plist>
"""
    plist_path.write_text(plist_content, encoding="utf-8")
    plist_path.chmod(0o644)

    result = subprocess.run(
        ["launchctl", "load", str(plist_path)],
        capture_output=True, text=True,
    )

    if result.returncode != 0:
        plist_path.unlink(missing_ok=True)
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ launchctl: {result.stderr.strip()}")
        return ""

    return label


def _schedule_linux(target_dt: datetime, task_name: str,
                    script_path: Path) -> str:

    if shutil.which("systemd-run"):
        on_calendar = target_dt.strftime("%Y-%m-%d %H:%M:00")
        result = subprocess.run(
            [
                "systemd-run",
                "--user",
                f"--on-calendar={on_calendar}",
                f"--unit={task_name}",
                "--",
                sys.executable, str(script_path),
            ],
            capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ⚠️ systemd-run failed: {result.stderr.strip()}, trying 'at'")

    if shutil.which("at"):
        at_time = target_dt.strftime("%H:%M %Y-%m-%d")
        cmd_str = f"{sys.executable} {script_path}\n"
        result  = subprocess.run(
            ["at", at_time],
            input=cmd_str, capture_output=True, text=True,
        )
        if result.returncode == 0:
            return task_name
        print(f"[Reminder] ❌ at: {result.stderr.strip()}")
        return ""

    print("[Reminder] ❌ Neither systemd-run nor at found on this Linux system.")
    return ""

def reminder(
    parameters: dict,
    response=None,
    player=None,
    session_memory=None,
) -> str:

    date_str = parameters.get("date", "").strip()
    time_str = parameters.get("time", "").strip()
    message  = parameters.get("message", "Reminder").strip()
    escalation = parameters.get("escalation")

    if not date_str or not time_str:
        return "I need both a date and a time to set a reminder."

    try:
        target_dt = datetime.strptime(f"{date_str} {time_str}", "%Y-%m-%d %H:%M")
    except ValueError:
        return "I couldn't parse that date or time. Please use YYYY-MM-DD and HH:MM."

    if target_dt <= datetime.now():
        return "That time has already passed — I can't set a reminder in the past."

    os_name    = _get_os()
    safe_msg   = _sanitise(message)
    escalation_enabled = (
        isinstance(escalation, dict) and bool(escalation.get("enabled", False))
    )
    normalized_escalation = {}
    if escalation_enabled:
        try:
            normalized_escalation = normalize_escalation_config(escalation)
            if not normalized_escalation["whatsapp_contact_name"]:
                return (
                    "Escalation was requested, but the WhatsApp contact name "
                    "was not provided."
                )
            if not normalized_escalation["messenger_contact_name"]:
                return (
                    "Escalation was requested, but the Messenger contact name "
                    "was not provided."
                )
        except Exception as e:
            return f"Invalid escalation settings: {e}"
        # Keep the normal notification useful even when the assistant is asleep.
        safe_msg = _sanitise(
            f"{safe_msg} — say 'acknowledged' when you have handled this."
        )
    task_name  = f"JARVISReminder_{target_dt.strftime('%Y%m%d_%H%M%S')}"

    try:
        script_path = _write_notify_script(task_name, safe_msg, os_name)
    except Exception as e:
        return f"Could not prepare the reminder script: {e}"

    try:
        if os_name == "windows":
            job_id = _schedule_windows(target_dt, task_name, script_path, safe_msg)
        elif os_name == "mac":
            job_id = _schedule_mac(target_dt, task_name, script_path)
        else:
            job_id = _schedule_linux(target_dt, task_name, script_path)
    except Exception as e:
        script_path.unlink(missing_ok=True)
        print(f"[Reminder] ❌ Scheduling exception: {e}")
        return "Something went wrong while scheduling the reminder."

    if not job_id:
        return "I couldn't register the reminder with the system scheduler."

    if escalation_enabled:
        try:
            register_escalation(
                reminder_id=task_name,
                target=target_dt,
                message=message,
                config=normalized_escalation,
            )
        except Exception as e:
            print(f"[Reminder] ❌ Escalation registration failed: {e}")
            return (
                "The normal reminder was set, but I could not register its "
                f"escalation: {e}"
            )

    if player:
        player.write_log(f"[Reminder] ✅ {date_str} {time_str} — {safe_msg[:40]}")

    friendly_time = target_dt.strftime("%B %d at %I:%M %p")
    if escalation_enabled:
        return (
            f"Reminder set for {friendly_time}; escalation is enabled. "
            "I will wait for your acknowledgement before contacting anyone."
        )
    return f"Reminder set for {friendly_time}."


# ── Tool declaration (auto-discovered by core/action_loader.py) ──────────────
TOOL = {
    "name": "reminder",
    "description": (
        "Sets a timed reminder using the operating system scheduler. "
        "Normal reminders do not contact anyone. Only include escalation when "
        "the user explicitly asks for it. Escalation sends WhatsApp to the exact "
        "configured contact, then makes a best-effort Messenger call attempt "
        "after the contact timeout."
    ),
    "parameters": {
        "type": "OBJECT",
        "properties": {
            "date": {
                "type": "STRING",
                "description": "Date in YYYY-MM-DD format"
            },
            "time": {
                "type": "STRING",
                "description": "Time in HH:MM format (24h)"
            },
            "message": {
                "type": "STRING",
                "description": "Reminder message text"
            },
            "escalation": {
                "type": "OBJECT",
                "description": (
                    "Optional. Include only when the user explicitly requests "
                    "escalation. WhatsApp contact must be 'Baba'; Messenger "
                    "contact must be 'شريف كمال'. Use natural Egyptian Arabic "
                    "for initial_message."
                ),
                "properties": {
                    "enabled": {
                        "type": "BOOLEAN",
                        "description": "True only for an explicit escalation request"
                    },
                    "whatsapp_contact_name": {
                        "type": "STRING",
                        "description": "Exact WhatsApp contact name: Baba"
                    },
                    "messenger_contact_name": {
                        "type": "STRING",
                        "description": "Exact Messenger contact name: شريف كمال"
                    },
                    "messenger_escalation_url": {
                        "type": "STRING",
                        "description": (
                            "Direct Messenger conversation URL used for escalation; "
                            "do not search Messenger contacts"
                        )
                    },
                    "initial_message": {
                        "type": "STRING",
                        "description": "Natural Egyptian Arabic WhatsApp message"
                    },
                    "user_response_timeout_minutes": {
                        "type": "INTEGER",
                        "description": "Minutes to wait for the user acknowledgement"
                    },
                    "contact_response_timeout_minutes": {
                        "type": "INTEGER",
                        "description": "Minutes to wait after WhatsApp before the call attempt"
                    },
                    "messenger_call_enabled": {
                        "type": "BOOLEAN",
                        "description": "Whether to attempt the Messenger call"
                    },
                    "conversation_language": {
                        "type": "STRING",
                        "description": "Language for the attempted conversation"
                    },
                    "max_call_duration_minutes": {
                        "type": "INTEGER",
                        "description": "Maximum intended call duration"
                    }
                }
            }
        },
        "required": [
            "date",
            "time",
            "message"
        ]
    },
    "handler": reminder,
}
